function AppendBLCMAESLSTRDebugRecord(Problem,generation,upperFE,totalFElower,mode, ...
    feasibleRate,historyWindowN,newKnowledgeN,Archive,FeedbackArchive,stats)
% Append generation-level diagnostics for BLCMAES-LSTR historical reuse.

    folder = fileparts(mfilename('fullpath'));
    file = fullfile(folder,'BLCMAESLSTR_lstr_debug.csv');
    writeHeader = ~exist(file,'file');

    fid = fopen(file,'a');
    if fid < 0
        return;
    end

    cleaner = onCleanup(@()fclose(fid));
    if writeHeader
        fprintf(fid,['Problem,D,DU,DL,Generation,UpperFE,TotalLowerFE,Mode,FeasibleRate,', ...
            'HistoryWindowN,NewKnowledgeN,FeasibilityArchiveN,BalancedArchiveN,ObjectiveArchiveN,', ...
            'FeedbackArchiveN,TotalOffspring,UsableN,AcceptedN,NoCorrectionRatio,', ...
            'MeanCandidateAll,MeanCandidateDistance,MeanCandidateImprovement,MeanCandidateNDS,', ...
            'MeanUsedN,MeanM,MeanDNew,MeanDist,MeanHistoricalImprovement,', ...
            'MeanRdist,MeanRdir,MeanRnum,MeanR,MedianR,MeanLambda,', ...
            'ZeroLambdaN,MeanDRawNorm,MeanLambdaDRawNorm,MeanDeltaFinalNorm,SigmaClippedN\n']);
    end

    fprintf(fid,['%s,%d,%d,%d,%d,%d,%d,%s,%.12g,', ...
        '%d,%d,%d,%d,%d,%d,%d,%d,%d,%.12g,', ...
        '%.12g,%.12g,%.12g,%.12g,%.12g,%.12g,%.12g,%.12g,%.12g,%.12g,', ...
        '%.12g,%.12g,%.12g,%.12g,%.12g,%d,%.12g,%.12g,%.12g,%d\n'], ...
        class(Problem),Problem.D,Problem.DU,Problem.DL,generation,upperFE,totalFElower,mode,feasibleRate, ...
        historyWindowN,newKnowledgeN,ArchiveSize(Archive,'Feasibility'), ...
        ArchiveSize(Archive,'Balanced'),ArchiveSize(Archive,'Objective'), ...
        size(FeedbackArchive.X,1),stats.total,stats.usable,stats.accepted, ...
        stats.noCorrectionRatio,stats.meanCandidateAll,stats.meanCandidateDistance, ...
        stats.meanCandidateImprovement,stats.meanCandidateNDS,stats.meanUsedN, ...
        stats.meanM,stats.meanDNew,stats.meanDist,stats.meanImprovement, ...
        stats.meanRdist,stats.meanRdir,stats.meanRnum,stats.meanR, ...
        stats.medianR,stats.meanLambda,stats.zeroLambda,stats.meanDRawNorm, ...
        stats.meanLambdaDRawNorm,stats.meanDeltaFinalNorm,stats.sigmaClipped);
    clear cleaner
end

function n = ArchiveSize(Archive,fieldName)
    if isfield(Archive,fieldName)
        n = size(Archive.(fieldName).X0,1);
    else
        n = 0;
    end
end
