classdef BLRLEA2 < ALGORITHM
    % <2024> <multi> <real> <constrained/none> <bilevel>
    methods
        function main(Algorithm,Problem)
            %% PPO parameters
            sigma0 = 1;
            ppoRatio = 0.5;
            stateDim = 10;
            actionDim = 2 * Problem.DU;
            hiddenDim = 32;
            learnRate = 1e-3;

            rolloutUpdateGap = 3;
            rolloutGenCount  = 0;
            rolloutBuffer    = InitializePPOBuffer();

            Actor  = InitializeActorNetwork(stateDim,actionDim,hiddenDim,learnRate);
            Critic = InitializeCriticNetwork(stateDim,hiddenDim,learnRate);

            %%总下层评估次数
            totalFElower = 0;
            %Generate random population
            ulPopDec = unifrnd(...
                repmat(Problem.lower(1:Problem.DU),Problem.N,1),...
                repmat(Problem.upper(1:Problem.DU),Problem.N,1));

            llPopDec = zeros(Problem.N,Problem.DL);

            for i = 1 : size(ulPopDec,1)
                [llPopDec(i,:),totalFElower] = llSearch(Problem,ulPopDec(i,:),[],totalFElower);
            end
            Population = Problem.Evaluation([ulPopDec,llPopDec]);
            lastBest = min(CalFitness(Problem.C,Population));


            %% Debug log%可以删除,这只是保存日志文件
            gen = 1;
          fid = fopen('BLRLEA2_debug_log.txt','w');
fprintf(fid,'Gen\tUpperFE\tTotalLowerFE\tUpperFit\tLowerFit\tlowerGap\n');

            %% UL Optimization
            while Algorithm.NotTerminated(Population)
                OldPopulation = Population;
                %% 1. 构造 PPO 状态
                state = BuildState(Problem,Population,lastBest);
                %% 2. PPO 输出动作
                value = CriticForward(Critic,state);
                [action,logProb,actionMean,actionStd] = ActorForward(Actor,state);
                Theta = ActionToParam(action,Problem,Population,sigma0);
                %% 3. Generate upper-level offspring by PPO and SBX+PM

                Fitness = CalFitness(Problem.C,Population);

                Noff = Problem.N;

                % Half offspring generated by PPO, half by SBX+PM
                Nppo = ppoRatio*Noff;
                Nea  = Noff - Nppo;

                %% 3.1 PPO offspring
                ulPPO = GenerateUpperOffspring(Theta,Problem,Nppo);

                %% 3.2 SBX + polynomial mutation offspring
                MatingPool = TournamentSelection(2,Nea,Fitness);
                ParentDec  = Population(MatingPool).decs;

                ulEA = OperatorSBXPM( ...
                    ParentDec(:,1:Problem.DU), ...
                    Problem.lower(1:Problem.DU), ...
                    Problem.upper(1:Problem.DU));

                %% 3.3 Merge offspring
                % Important: PPO offspring must be placed first
                % because RewardCalculator uses Offspring(1:Nppo)
                ulOffDec = [ulPPO;ulEA];

                %% 6. 给每个上层子代找最近旧个体的下层解
                AllDec = Population.decs;
                AllUL  = AllDec(:,1:Problem.DU);

                [~,closest] = min(pdist2(ulOffDec,AllUL),[],2);

                llOffDec = zeros(size(ulOffDec,1),Problem.DL);

                for i = 1 : size(ulOffDec,1)
                    [llOffDec(i,:),totalFElower] = llSearch( ...
                        Problem, ...
                        ulOffDec(i,:), ...
                        AllDec(closest(i),Problem.DU+1:end),totalFElower);
                end

                %% 7. 评价完整子代
                Offspring = Problem.Evaluation([ulOffDec,llOffDec]);
                %% 8. 计算 reward 和 next state
                reward = RewardCalculator(Problem,OldPopulation,Offspring,Nppo);

                %% 9. 环境选择
                Population = EnvironmentalSelectionUpper(Problem,Population,Offspring);

                %% Print best upper individual and its lower-level value
             %% Print and save best individual information
             %% Record best solution information
          

            %% 10. Record best upper and lower information
            Fitness = CalFitness(Problem.C,Population);
            [UpperFit,best] = min(Fitness);

            bestDec = Population(best).dec;
            bestObj = Population(best).obj;
            bestCon = Population(best).con;

            %% Lower objective fitness and lowerGap
            if length(bestObj) >= 2
                FL = bestObj(2);

                xu1 = bestDec(1:Problem.p);

                problemName = class(Problem);

                switch problemName
                    case {'SMD1','SMD2','SMD3','SMD4','SMD5','SMD6'}
                        FLstar = sum(xu1.^2,2);

                    case 'SMD7'
                        FLstar = sum(xu1.^3,2);

                    case 'SMD8'
                        FLstar = sum(abs(xu1),2);

                    case {'SMD9','SMD10'}
                        FLstar = sum(xu1.^2,2);

                    case 'SMD11'
                        FLstar = sum(xu1.^2,2) + 1;

                    case 'SMD12'
                        FLstar = sum(xu1.^2,2) + 1;

                    otherwise
                        FLstar = nan;
                end

                if isnan(FLstar)
                    lowerGap = inf;
                else
                    lowerGap = abs(FL - FLstar);
                end
            else
                FL = nan;
                lowerGap = inf;
            end

            %% Lower-level constraint violation
            if isempty(bestCon) || length(bestCon) < Problem.C + 1
                LLCV = 0;
            else
                llCon = bestCon(Problem.C+1:end);

                if isempty(llCon)
                    LLCV = 0;
                else
                    LLCV = sum(max(0,llCon));
                end
            end

            %% LowerFit is lower-level fitness, not lowerGap
            % If lower-level constraints are feasible:
            %     LowerFit = FL
            % Otherwise:
            %     LowerFit = LLCV + 1e10
            if LLCV <= 0
                LowerFit = FL;
            else
                LowerFit = LLCV + 1e10;
            end

            %% Print to command window
            fprintf('Gen=%4d | UpperFE=%6d | TotalLowerFE=%10d | UpperFit=%.6e | LowerFit=%.6e | lowerGap=%.6e\n', ...
                gen, Problem.FE, totalFElower, UpperFit, LowerFit, lowerGap);

            %% Save to BLRLEA2_debug_log.txt
            fprintf(fid,'%d\t%d\t%d\t%.12e\t%.12e\t%.12e\n', ...
                gen, Problem.FE, totalFElower, UpperFit, LowerFit, lowerGap);

            drawnow;

            %% Upper-level termination by upper fitness
            upperTol = 1e-6;

            if abs(UpperFit) <= upperTol
                fprintf('Upper optimum reached: UpperFit = %.6e, UpperFE = %d, TotalLowerFE = %d\n', ...
                    UpperFit, Problem.FE, totalFElower);
                break;
            end

            gen = gen + 1;
                %%中间是新加打印代码

                currentBest = min(CalFitness(Problem.C,OldPopulation));
                nextState = BuildState(Problem,Population,currentBest);

                %% 10. 存 PPO buffer
                oneBuffer = InitializePPOBuffer();

                oneBuffer.states       = state;
                oneBuffer.actions      = action;
                oneBuffer.rewards      = reward;
                oneBuffer.next_states  = nextState;
                oneBuffer.log_probs    = logProb;
                oneBuffer.values       = value;
                oneBuffer.action_means = actionMean;
                oneBuffer.action_stds  = actionStd;
                oneBuffer.dones        = 0;

                rolloutBuffer = AppendPPOBuffer(rolloutBuffer,oneBuffer);
                rolloutGenCount = rolloutGenCount + 1;

                %% 11. PPO 更新
                if rolloutGenCount >= rolloutUpdateGap
                    rolloutBuffer.dones(end) = 1;
                    [Actor,Critic] = PPOUpdate(Actor,Critic,rolloutBuffer);

                    rolloutBuffer = InitializePPOBuffer();
                    rolloutGenCount = 0;
                end

                lastBest = min(CalFitness(Problem.C,Population));
            end

            fclose(fid);
        end
    end
end


