function reward = RewardCalculator(Problem,OldPopulation,Offspring,Nppo)
% Reward calculated only from PPO-generated offspring.
%
% Offspring(1:Nppo) are assumed to be generated by PPO.
% Offspring(Nppo+1:end) are generated by EA/PCX and are ignored here.

    %% Extract PPO offspring only
    PPOOffspring = Offspring(1:Nppo);

    oldFit = CalFitness(Problem.C,OldPopulation);
    ppoFit = CalFitness(Problem.C,PPOOffspring);

    oldBest = min(oldFit);
    oldMean = mean(oldFit);
    oldMedian = median(oldFit);

    ppoBest = min(ppoFit);
    ppoMean = mean(ppoFit);

    %% 1. PPO best improvement over old population best
    rBest = (oldBest - ppoBest) / (abs(oldBest) + 1e-8);

    %% 2. PPO mean improvement over old population mean
    rMean = (oldMean - ppoMean) / (abs(oldMean) + 1e-8);

    %% 3. PPO offspring quality rate
    % Count how many PPO offspring are better than the old median individual
    betterRate = mean(ppoFit < oldMedian);
    rBetter = 2 * betterRate - 1;

    %% 4. PPO feasibility reward
    ppoCon = PPOOffspring.cons;

    if isempty(ppoCon)
        feasRate = 1;
        meanCV = 0;
    else
        cv = sum(max(0,ppoCon),2);
        feasRate = mean(cv <= 0);
        meanCV = mean(cv);
    end

    rFeas = 2 * feasRate - 1;
    rCV   = -log1p(meanCV);

    %% Combine reward
    reward = 1.0*rBest + 0.3*rMean + 0.3*rBetter + 0.2*rFeas + 0.1*rCV;

    %% Clip reward
    reward = max(min(reward,5),-5);
end