function [rewards,stats] = RewardCalculator( ...
    Problem,OldPopulation,Offspring,Nppo,ppoSurvived,deltaPPO,perturbScale)
% Reward calculated per PPO-perturbed offspring.
%
% Offspring(1:Nppo) are assumed to be generated by PPO.
% Offspring(Nppo+1:end) are generated by EA/PCX and are ignored here.

    PPOOffspring = Offspring(1:Nppo);

    oldFit = CalFitness(Problem.C,OldPopulation);
    ppoFit = CalFitness(Problem.C,PPOOffspring);
    oldFit = oldFit(:);
    ppoFit = ppoFit(:);

    oldBest = min(oldFit);
    oldMedian = median(oldFit);

    sortedFit = sort(ppoFit);
    trimCount = max(1,floor(0.1*numel(sortedFit)));
    if 2 * trimCount < numel(sortedFit)
        ppoTrimMean = mean(sortedFit(trimCount+1:end-trimCount));
    else
        ppoTrimMean = mean(sortedFit);
    end

    ppoCon = PPOOffspring.cons;
    if isempty(ppoCon)
        ppoFeasible = true(Nppo,1);
    else
        if Problem.C > 0
            ppoCon = ppoCon(:,1:Problem.C);
        else
            ppoCon = zeros(Nppo,1);
        end
        ppoFeasible = sum(max(0,ppoCon),2) <= 0;
    end
    ppoFeasRate = mean(ppoFeasible);

    if nargin < 5 || isempty(ppoSurvived)
        ppoSurvived = false(Nppo,1);
    end
    ppoSurvived = logical(ppoSurvived(:));

    if nargin < 6 || isempty(deltaPPO)
        deltaPPO = zeros(Nppo,Problem.DU);
    end
    if nargin < 7 || isempty(perturbScale)
        perturbScale = ones(1,Problem.DU);
    end

    perturbScale = perturbScale(:)';
    scaleMat = repmat(perturbScale,Nppo,1);
    stepSize = mean(abs(deltaPPO ./ (scaleMat + 1e-12)),2);

    rQuality = tanh((oldMedian - ppoFit) ./ (abs(oldMedian) + 1e-8));
    rBest    = tanh((oldBest - ppoFit) ./ (abs(oldBest) + 1e-8));
    rBetter  = 2 * double(ppoFit < oldMedian) - 1;
    rSurvive = 2 * double(ppoSurvived) - 1;
    rFeas    = 2 * double(ppoFeasible) - 1;
    rStep    = -stepSize;

    rewards = 0.35 * rQuality + 0.20 * rBest + ...
              0.25 * rBetter  + 0.15 * rSurvive + ...
              0.05 * rFeas    + 0.05 * rStep;
    rewards = max(min(rewards,1),-1);

    stats.betterRate = mean(ppoFit < oldMedian);
    stats.trimMean   = ppoTrimMean;
    stats.feasRate   = ppoFeasRate;
    stats.meanReward = mean(rewards);
    stats.meanStep   = mean(stepSize);
end
