function Offspring_ulpop_ea = GenerateEAOffspring(ulPop, Problem, N_ea, proC, disC, proM, disM)
% GenerateEAOffspring
% Generate upper-level offspring by SBX crossover and polynomial mutation
%
% Input:
%   ulPop    : N x DU current upper-level population
%   Problem  : PlatEMO problem object
%   N_ea     : number of offspring required
%   proC     : crossover probability
%   disC     : crossover distribution index
%   proM     : mutation probability
%   disM     : mutation distribution index
%
% Output:
%   Offspring_ulpop_ea : N_ea x DU offspring generated by EA

    [N, DU] = size(ulPop);

    % ===== 1. 如果父代数量不足，直接报错 =====
    if N < 2
        error('GenerateEAOffspring: parent population size must be at least 2.');
    end

    % ===== 2. 为了得到足够多子代，先准备配对父代 =====
    pair_num = ceil(N_ea / 2);   % 每对父代产生2个子代
    parent_idx = randi(N, 2 * pair_num, 1);
    Parent = ulPop(parent_idx, :);

    Parent1 = Parent(1:pair_num, :);
    Parent2 = Parent(pair_num+1:end, :);

    % ===== 3. SBX 交叉 =====
    beta = zeros(pair_num, DU);
    mu   = rand(pair_num, DU);

    beta(mu <= 0.5) = (2 * mu(mu <= 0.5)).^(1 / (disC + 1));
    beta(mu > 0.5)  = (2 - 2 * mu(mu > 0.5)).^(-1 / (disC + 1));

    beta = beta .* (-1).^randi([0,1], pair_num, DU);
    beta(rand(pair_num, DU) < 0.5) = 1;
    beta(repmat(rand(pair_num,1) > proC, 1, DU)) = 1;

    Offspring = [(Parent1 + Parent2)/2 + beta .* (Parent1 - Parent2)/2;
                 (Parent1 + Parent2)/2 - beta .* (Parent1 - Parent2)/2];

    % ===== 4. 多项式变异 =====
    Lower = repmat(Problem.lower(1:DU), 2 * pair_num, 1);
    Upper = repmat(Problem.upper(1:DU), 2 * pair_num, 1);

    Site = rand(2 * pair_num, DU) < proM / DU;
    mu   = rand(2 * pair_num, DU);

    % 先边界截断，避免数值越界
    Offspring = min(max(Offspring, Lower), Upper);

    % mu <= 0.5 的部分
    temp = Site & mu <= 0.5;
    Offspring(temp) = Offspring(temp) + ...
        (Upper(temp) - Lower(temp)) .* ...
        ((2 .* mu(temp) + ...
        (1 - 2 .* mu(temp)) .* ...
        (1 - (Offspring(temp) - Lower(temp)) ./ (Upper(temp) - Lower(temp))).^(disM + 1)).^(1 / (disM + 1)) - 1);

    % mu > 0.5 的部分
    temp = Site & mu > 0.5;
    Offspring(temp) = Offspring(temp) + ...
        (Upper(temp) - Lower(temp)) .* ...
        (1 - (2 .* (1 - mu(temp)) + ...
        2 .* (mu(temp) - 0.5) .* ...
        (1 - (Upper(temp) - Offspring(temp)) ./ (Upper(temp) - Lower(temp))).^(disM + 1)).^(1 / (disM + 1)));

    % ===== 5. 再次边界修复 =====
    Offspring = min(max(Offspring, Lower), Upper);

    % ===== 6. 截取前 N_ea 个子代 =====
    Offspring_ulpop_ea = Offspring(1:N_ea, :);
end