classdef BLRLEA2_NoPPO < ALGORITHM
    % <2024> <multi> <real> <constrained/none> <bilevel>
    methods
        function main(Algorithm,Problem)

            %% Parameters
            sigma0     = 1;
            ppoRatio   = 0.5;

            %% Total lower-level function evaluations
            totalFElower = 0;

            %% Generate random upper-level population
            ulPopDec = unifrnd( ...
                repmat(Problem.lower(1:Problem.DU),Problem.N,1), ...
                repmat(Problem.upper(1:Problem.DU),Problem.N,1));

            %% Lower-level search for initial population
            llPopDec = zeros(Problem.N,Problem.DL);

            for i = 1 : size(ulPopDec,1)
                [llPopDec(i,:),totalFElower] = llSearch( ...
                    Problem, ...
                    ulPopDec(i,:), ...
                    [], ...
                    totalFElower);
            end

            Population = Problem.Evaluation([ulPopDec,llPopDec]);
            upperTol = 1e-5;
            upperReached = false;

            %% Debug log
            gen = 1;
            fid = fopen('BLRLEA2_NoPPO_debug_log.txt','w');
            logCleaner = onCleanup(@()CloseLogFile(fid));
            fprintf(fid,'Gen\tUpperFE\tTotalLowerFE\tUpperFit\tLowerFit\tlowerGap\n');

            %% Upper-level optimization
            while Algorithm.NotTerminated(Population)
                if upperReached
                    break;
                end

                %% 1. Calculate upper-level fitness
                Fitness = CalFitness(Problem.C,Population);

                %% 2. Generate upper-level offspring
                Noff = Problem.N;

                % Half offspring generated by elite-distribution anchors,
                % half offspring generated by SBX + polynomial mutation
                Nppo = floor(ppoRatio*Noff);
                Nea  = Noff - Nppo;

                %% 2.1 Elite-distribution anchors without PPO perturbation
                ThetaBase = BuildEliteTheta(Problem,Population,sigma0);
                basePPO = GenerateUpperOffspring(ThetaBase,Problem,Nppo);

                % Ablation of BLRLEA2: remove the PPO decision-variable
                % perturbation, i.e., deltaPPO = 0 and ulPPO = basePPO.
                ulPPO = basePPO;

                %% 2.2 SBX + polynomial mutation offspring
                MatingPool = TournamentSelection(2,Nea,Fitness);
                ParentDec  = Population(MatingPool).decs;

                ulEA = OperatorSBXPM( ...
                    ParentDec(:,1:Problem.DU), ...
                    Problem.lower(1:Problem.DU), ...
                    Problem.upper(1:Problem.DU));

                %% 2.3 Merge upper-level offspring
                ulOffDec = [ulPPO;ulEA];

                %% 3. Lower-level search
                AllDec = Population.decs;
                AllUL  = AllDec(:,1:Problem.DU);

                [~,closest] = min(pdist2(ulOffDec,AllUL),[],2);

                llOffDec = zeros(size(ulOffDec,1),Problem.DL);

                for i = 1 : size(ulOffDec,1)
                    [llOffDec(i,:),totalFElower] = llSearch( ...
                        Problem, ...
                        ulOffDec(i,:), ...
                        AllDec(closest(i),Problem.DU+1:end), ...
                        totalFElower);
                end

                %% 4. Evaluate complete offspring
                Offspring = Problem.Evaluation([ulOffDec,llOffDec]);

                %% 5. Upper-level environmental selection
                Population = EnvironmentalSelectionUpper(Problem,Population,Offspring);

                %% 6. Record best information
                Fitness = CalFitness(Problem.C,Population);
                [UpperFit,best] = min(Fitness);

                bestDec = Population(best).dec;
                bestObj = Population(best).obj;
                bestCon = Population(best).con;

                [LowerFit,lowerGap] = CalOneLowerFitness(Problem,bestDec,bestObj,bestCon);

                fprintf('NoPPO Gen=%4d | UpperFE=%6d | TotalLowerFE=%10d | UpperFit=%.6e | LowerFit=%.6e | lowerGap=%.6e\n', ...
                    gen, Problem.FE, totalFElower, UpperFit, LowerFit, lowerGap);

                fprintf(fid,'%d\t%d\t%d\t%.12e\t%.12e\t%.12e\n', ...
                    gen, Problem.FE, totalFElower, UpperFit, LowerFit, lowerGap);

                drawnow;

                %% 7. Upper-level termination by upper fitness
                if UpperFit <= upperTol
                    upperReached = true;
                    fprintf('NoPPO upper optimum reached: UpperFit = %.6e, UpperFE = %d, TotalLowerFE = %d\n', ...
                        UpperFit, Problem.FE, totalFElower);
                end

                gen = gen + 1;
            end
        end
    end
end

function CloseLogFile(fid)
    if ~isempty(fid) && isnumeric(fid) && fid > 0
        fclose(fid);
    end
end


function Theta = BuildEliteTheta(Problem,Population,sigma0)
% Build the same elite-sampling distribution as BLRLEA2.
% No PPO decision-variable perturbation is applied in this ablation.

    PopDec  = Population.decs;
    ulPop   = PopDec(:,1:Problem.DU);
    fitness = CalFitness(Problem.C,Population);

    [N,DU] = size(ulPop);

    [~,rank] = sort(fitness,'ascend');

    eliteNum = max(2,ceil(0.2*N));
    elitePop = ulPop(rank(1:eliteNum),:);

    eliteMean = mean(elitePop,1);

    popStd = std(ulPop,0,1);
    popStd(popStd < 1e-6) = 1e-6;

    minSigma = AdaptiveMinSigma(Problem,Population,DU);
    perturbScale = max(popStd,minSigma);

    mu    = eliteMean;
    sigma = sigma0 .* exp(-0.3) .* perturbScale;

    lower = Problem.lower(1:DU);
    upper = Problem.upper(1:DU);

    mu    = min(max(mu,lower),upper);
    sigma = max(sigma,1e-6);

    Theta.mu    = mu;
    Theta.sigma = sigma;
end


function minSigma = AdaptiveMinSigma(Problem,Population,DU)

    range = Problem.upper(1:DU) - Problem.lower(1:DU);
    range(range < 1e-12) = 1;

    fitness = CalFitness(Problem.C,Population);
    bestAbs = abs(min(fitness));

    if bestAbs > 1e-2
        scale = 0.02;
    elseif bestAbs > 1e-4
        scale = 0.005;
    else
        scale = 1e-5;
    end

    minSigma = max(scale .* range,1e-6);
end


function [LowerFit,lowerGap] = CalOneLowerFitness(Problem,Dec,Obj,Con)
% Calculate lower-level fitness and lower-level gap for one complete solution.
%
% LowerFit:
%   If lower-level constraints are feasible:
%       LowerFit = FL
%   Otherwise:
%       LowerFit = LLCV + 1e10
%
% lowerGap:
%   lowerGap = abs(FL - FLstar(xu))

    %% Lower-level objective value
    if length(Obj) >= 2
        FL = Obj(2);
    else
        FL = nan;
    end

    %% lowerGap = abs(FL - FLstar)
    lowerGap = CalOneLowerGap(Problem,Dec,Obj);

    %% Lower-level constraint violation
    if isempty(Con) || length(Con) < Problem.C + 1
        LLCV = 0;
    else
        llCon = Con(Problem.C+1:end);

        if isempty(llCon)
            LLCV = 0;
        else
            LLCV = sum(max(0,llCon));
        end
    end

    %% LowerFit follows lower-level fitness logic
    if LLCV <= 0
        LowerFit = FL;
    else
        LowerFit = LLCV + 1e10;
    end
end


function lowerGap = CalOneLowerGap(Problem,Dec,Obj)
% lowerGap = abs(FL - FLstar(xu))

    problemName = class(Problem);

    if length(Obj) < 2
        lowerGap = nan;
        return;
    end

    FL = Obj(2);

    if ~isprop(Problem,'p') || ~isprop(Problem,'r') || ~isprop(Problem,'q')
        lowerGap = nan;
        return;
    end

    xu1 = Dec(1:Problem.p);

    switch problemName

        case {'SMD1','SMD2','SMD3','SMD4','SMD5','SMD6'}
            FLstar = sum(xu1.^2,2);

        case 'SMD7'
            FLstar = sum(xu1.^3,2);

        case 'SMD8'
            FLstar = sum(abs(xu1),2);

        case {'SMD9','SMD10'}
            FLstar = sum(xu1.^2,2);

        case 'SMD11'
            FLstar = sum(xu1.^2,2) + 1;

        case 'SMD12'
            FLstar = sum(xu1.^2,2) + 1;

        otherwise
            lowerGap = nan;
            return;
    end

    lowerGap = abs(FL - FLstar);
end
